<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.5                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2014                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 *
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2014
 *
 * Generated from xml/schema/CRM/Mailing/Mailing.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_VoiceBroadcast_DAO_VoiceBroadcastCalls extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   * @static
   */
  static $_tableName = 'civicrm_voicebroadcast_calls';
  /**
   * static instance to hold the field values
   *
   * @var array
   * @static
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   * @static
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   * @static
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   * @static
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   * @static
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   * @static
   */
  static $_log = false;
  /**
   *
   * @var int unsigned
   */
  public $id;
  /**
   * Which site is this mailing for
   *
   * @var int unsigned
   */
  public $total_cost;
  /**
   * Mailing Name.
   *
   * @var string
   */
  public $direction;
  /**
   * From Header of mailing
   *
   * @var string
   */
  public $hangup_cause;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $from;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $bill_duration;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $bill_rate;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $to;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $answer_time;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $start_time;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $call_uuid;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $duration;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $request_uuid;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $end_time;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $call_status;
  /**
   * Subject of mailing
   *
   * @var string
   */
  public $event;

  /**
   * class constructor
   *
   * @access public
   * @return civicrm_mailing
   */
  function __construct()
  {
    $this->__table = 'civicrm_voicebroadcast_calls';
    parent::__construct();
  }
  /**
   * return foreign keys and entity references
   *
   * @static
   * @access public
   * @return array of CRM_Core_Reference_Interface
   */
  static function getReferenceColumns()
  {
    if (!self::$_links) {
      self::$_links = static ::createReferenceColumns(__CLASS__);
    }
    return self::$_links;
  }
  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'required' => true,
        ) ,
        'total_cost' => array(
          'name' => 'total_cost',
          'type' => CRM_Utils_Type::T_FLOAT,
        ) ,
        'direction' => array(
          'name' => 'direction',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'hangup_cause' => array(
          'name' => 'hangup_cause',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'from' => array(
          'name' => 'from',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'bill_duration' => array(
          'name' => 'bill_duration',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'bill_rate' => array(
          'name' => 'bill_rate',
          'type' => CRM_Utils_Type::T_FLOAT,
        ) ,
        'to' => array(
          'name' => 'to',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'answer_time' => array(
          'name' => 'answer_time',
          'type' => CRM_Utils_Type::T_DATE,
        ) ,
        'start_time' => array(
          'name' => 'start_time',
          'type' => CRM_Utils_Type::T_DATE,
        ) ,
        'call_uuid' => array(
          'name' => 'call_uuid',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'duration' => array(
          'name' => 'duration',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'request_uuid' => array(
          'name' => 'request_uuid',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'end_time' => array(
          'name' => 'end_time',
          'type' => CRM_Utils_Type::T_DATE,
        ) ,
        'call_status' => array(
          'name' => 'call_status',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
        'event' => array(
          'name' => 'event',
          'type' => CRM_Utils_Type::T_STRING,
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @access public
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'total_cost' => 'total_cost',
        'direction' => 'direction',
        'hangup_cause' => 'hangup_cause',
        'from' => 'from',
        'bill_duration' => 'bill_duration',
        'bill_rate' => 'bill_rate',
        'to' => 'to',
        'answer_time' => 'answer_time',
        'start_time' => 'start_time',
        'call_uuid' => 'call_uuid',
        'duration' => 'duration',
        'request_uuid' => 'request_uuid',
        'end_time' => 'end_time',
        'call_status' => 'call_status',
        'event' => 'event',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * returns the names of this table
   *
   * @access public
   * @static
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * returns if this table needs to be logged
   *
   * @access public
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * returns the list of fields that can be imported
   *
   * @access public
   * return array
   * @static
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['mailing'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * returns the list of fields that can be exported
   *
   * @access public
   * return array
   * @static
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['mailing'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}
